limit_req_zone $binary_remote_addr zone=global:10m rate=30r/s;

server {
    listen 80;
    server_name _;
    root /var/www/html/public;
    index index.php;

    location /healthz {
        access_log off;
        return 200 'OK';
        add_header Content-Type text/plain;
    }

    location / {
        limit_req zone=global burst=60 nodelay;
        limit_req_status 429;

        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        limit_req zone=global burst=60 nodelay;
        limit_req_status 429;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass app:9000;
    }
}
